name: CI

on:
  push:
  pull_request:

jobs:
  check-lint-test-build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://user:password@localhost:5432/db
      BETTER_AUTH_SECRET: some-secret-value-of-at-least-32-chars-long
      ORIGIN: http://localhost:5173
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm exec playwright install chromium --with-deps

      - name: Lint
        run: pnpm lint

      - name: Svelte-Check (Typescript)
        run: pnpm check

      - name: Unit Tests
        run: pnpm test:unit --run

      - name: E2E Tests
        run: pnpm test:e2e

      - name: Build
        run: pnpm build

      - name: Build Storybook
        run: pnpm build-storybook
